project:
  type: website
  resources: "images"

website:
  title: "Trey Stafford"
  navbar:
    left:
      - href: "blog/index.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



